plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  # - path: packages/plugin-dotenv/bundles/@yarnpkg/plugin-dotenv.js
  # - path: packages/workspaces-export/bundles/@yarnpkg/workspaces-export.js

yarnPath: .yarn/releases/yarn-sources.cjs
