changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  # - path: packages/plugin-release/bundles/@yarnpkg/plugin-release.js
  # - path: packages/plugin-workspaces-export/bundles/@yarnpkg/plugin-workspaces-export.js

yarnPath: .yarn/releases/yarn-sources.cjs
