on:
  workflow_dispatch:

name: "[Manual] Create release tags"

jobs:
  release:
    name: Create release tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Fetch tags
        run: git fetch --prune --tags -f
      - name: Set committer to github-actions
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Use Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Release packages
        run: ./scripts/release/01-release-tags.sh
      - name: Push release
        run: git push --follow-tags
