on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - release/*

name: Generate GitHub release

jobs:
  ghRelease:
    name: Generate GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --prune --tags -f
      - name: Use Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Build and publish packages
        run: ./scripts/release/02-release-builds.sh
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        run: ./scripts/release/03-release-github.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
